# Generated by Django 5.0.3 on 2024-03-18 19:56

import api.file_paths
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('code', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('type', models.CharField(choices=[('DISTRICT', 'District'), ('STATE', 'State'), ('COUNTRY', 'Country'), ('UT', 'Ut')], max_length=20)),
                ('parent_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.geography')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.file_paths._organization_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('homepage', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('organization_types', models.CharField(choices=[('STATE GOVERNMENT', 'State Government'), ('UNION TERRITORY GOVERNMENT', 'Union Territory Government'), ('URBAN LOCAL BODY', 'Urban Local Body'), ('ACADEMIC INSTITUTION', 'Academic Institution'), ('CENTRAL GOVERNMENT', 'Central Government'), ('CITIZENS GROUP', 'Citizens Group'), ('CIVIL SOCIETY ORGANISATION', 'Civil Society Organisation'), ('INDUSTRY BODY', 'Industry Body'), ('MEDIA ORGANISATION', 'Media Organisation'), ('OPEN DATA/TECHNOLOGY COMMUNITY', 'Open Data Technology Community'), ('PRIVATE COMPANY', 'Private Company'), ('PUBLIC SECTOR COMPANY', 'Public Sector Company'), ('OTHERS', 'Others'), ('STARTUP', 'Startup'), ('GOVERNMENT', 'Government'), ('CORPORATIONS', 'Corporations'), ('NGO', 'Ngo')], max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_field', to='api.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=75, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organization')),
            ],
        ),
    ]
