# Generated by Django 5.0.4 on 2024-10-17 18:09

import api.utils.file_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dataspace_dataset_dataspace'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.CharField(max_length=1000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=api.utils.file_paths._use_case_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('slug', models.SlugField(max_length=75, null=True, unique=True)),
                ('datasets', models.ManyToManyField(blank=True, to='api.dataset')),
            ],
        ),
    ]
