# Generated by Django 5.0.4 on 2024-10-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usecase'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50),
        ),
    ]
