# Generated by Django 5.0.3 on 2024-03-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_metadata_remove_dataset_title_datasetmetadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='options',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='validator',
            field=models.CharField(blank=True, max_length=75),
        ),
    ]
