# Generated by Django 5.0.4 on 2024-10-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_usecase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='slug',
            field=models.SlugField(blank=True, max_length=75, null=True, unique=True),
        ),
    ]
