# Generated by Django 5.0.4 on 2024-05-07 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tag_dataset_description_dataset_title_dataset_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('API', 'Api'), ('FILE', 'File'), ('EXTERNAL', 'External')], default='FILE', max_length=50),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('SELECT', 'Select'), ('MULTISELECT', 'Multiselect'), ('DATE', 'Date')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcemetadata',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource'),
        ),
        migrations.CreateModel(
            name='ResourceFileDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resources/')),
                ('size', models.FloatField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
            ],
        ),
    ]
