# Generated by Django 5.0.4 on 2024-10-22 12:41

import api.utils.file_paths
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_usecase_description_alter_usecase_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceChartImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.utils.file_paths._chart_image_directory_path)),
            ],
        ),
    ]
