# Generated by Django 5.0.4 on 2024-10-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resourcechartdetails_aggregate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='aggregate_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SUM', 'Sum'), ('MEAN', 'Average'), ('COUNT', 'Count')], default='NONE', max_length=50),
        ),
    ]
