# Generated by Django 5.0.4 on 2024-05-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_accessmodel_accessmodelresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessmodel',
            old_name='title',
            new_name='name',
        ),
    ]
