# Generated by Django 5.0.4 on 2024-10-23 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_resourcechartdetails_aggregate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcechartdetails',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='resourcechartimage',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chart_images', to='api.dataset'),
        ),
        migrations.AddField(
            model_name='resourcechartimage',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
