# Generated by Django 5.0.4 on 2024-05-13 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_title_accessmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcefiledetails',
            name='resource',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.resource'),
        ),
    ]
