# Generated by Django 5.0.4 on 2024-10-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_resourcechartdetails_modified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceschema',
            name='format',
            field=models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('INTEGER', 'Integer'), ('DATE', 'Date'), ('BOOLEAN', 'Boolean')], max_length=255),
        ),
    ]
