# Generated by Django 5.0.4 on 2024-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_resourceschema_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcechartdetails',
            name='filters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
