# Generated by Django 5.0.4 on 2024-05-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_resourcefiledetails_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcefiledetails',
            name='format',
            field=models.CharField(default='number', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ResourceSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('DATE', 'Date')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
            ],
        ),
    ]
