# Generated by Django 5.0.4 on 2025-02-26 14:07

import api.models.SerializableJSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_resourcechartdetails_filters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='aggregate_type',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='region_column',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='show_legend',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='value_column',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='x_axis_column',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='x_axis_label',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='y_axis_column',
        ),
        migrations.RemoveField(
            model_name='resourcechartdetails',
            name='y_axis_label',
        ),
        migrations.AddField(
            model_name='resourcechartdetails',
            name='options',
            field=api.models.SerializableJSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='chart_type',
            field=models.CharField(choices=[('BAR_VERTICAL', 'Bar Vertical'), ('BAR_HORIZONTAL', 'Bar Horizontal'), ('GROUPED_BAR_VERTICAL', 'Grouped Bar Vertical'), ('GROUPED_BAR_HORIZONTAL', 'Grouped Bar Horizontal'), ('LINE', 'Line'), ('MULTILINE', 'Multiline'), ('ASSAM_DISTRICT', 'Assam District'), ('ASSAM_RC', 'Assam Rc')], default='BAR_HORIZONTAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='filters',
            field=api.models.SerializableJSONField(blank=True, default=list, null=True),
        ),
    ]
