# Generated by Django 5.0.4 on 2024-05-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_dataset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessmodelresource',
            name='fields',
            field=models.ManyToManyField(to='api.resourceschema'),
        ),
    ]
