# Generated by Django 5.0.4 on 2024-05-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_accessmodelresource_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceschema',
            name='format',
            field=models.CharField(
                choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('INTEGER', 'Integer'), ('DATE', 'Date')],
                max_length=255),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                to='api.category')),
            ],
        ),
    ]
