# Generated by Django 5.0.4 on 2024-05-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_resourceschema_format_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodel',
            name='type',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private'), ('PROTECTED', 'Protected')], default='PUBLIC', max_length=100),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='data_standard',
            field=models.CharField(blank=True, choices=[('DCATV3', 'Dcatv3'), ('OCDS', 'Ocds'), ('OBDS', 'Obds'), ('NA', 'Na')], max_length=50),
        ),
    ]
