# Generated by Django 5.0.4 on 2025-03-13 11:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_dataset_slug_alter_resource_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDataTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('resource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
            ],
            options={
                'db_table': 'resource_data_table',
                'ordering': ['-modified'],
            },
        ),
    ]
