# Generated by Django 5.0.4 on 2024-05-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_accessmodel_type_alter_metadata_data_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='accessmodel',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
