# Generated by Django 5.0.4 on 2025-03-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_resourcedatatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
    ]
