# Generated by Django 5.0.4 on 2025-03-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_resource_download_count"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Category",
            new_name="Sector",
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={"verbose_name_plural": "sectors"},
        ),
        migrations.RenameField(
            model_name="dataset",
            old_name="categories",
            new_name="sectors",
        ),
        migrations.AlterModelTable(
            name="sector",
            table="sector",
        ),
    ]
