# Generated by Django 5.0.4 on 2024-05-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_dataset_categories_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=75),
            preserve_default=False,
        ),
    ]
