# Generated by Django 5.0.4 on 2025-04-10 07:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_rename_category_sector_alter_sector_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmetadata",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="usecase",
            name="running_status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="sectors",
            field=models.ManyToManyField(
                blank=True, related_name="usecases", to="api.sector"
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="tags",
            field=models.ManyToManyField(blank=True, to="api.tag"),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="model",
            field=models.CharField(
                choices=[
                    ("DATASET", "Dataset"),
                    ("RESOURCE", "Reseource"),
                    ("USECASE", "Usecase"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resourcechartdetails",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("BAR_VERTICAL", "Bar Vertical"),
                    ("BAR_HORIZONTAL", "Bar Horizontal"),
                    ("GROUPED_BAR_VERTICAL", "Grouped Bar Vertical"),
                    ("GROUPED_BAR_HORIZONTAL", "Grouped Bar Horizontal"),
                    ("LINE", "Line"),
                    ("MULTILINE", "Multiline"),
                    ("ASSAM_DISTRICT", "Assam District"),
                    ("ASSAM_RC", "Assam Rc"),
                    ("TREEMAP", "Treemap"),
                ],
                default="BAR_HORIZONTAL",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="resourcemetadata",
            name="metadata_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.metadata"
            ),
        ),
        migrations.CreateModel(
            name="UseCaseMetadata",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("value", models.CharField(max_length=1000)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "metadata_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.metadata"
                    ),
                ),
                (
                    "usecase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="api.usecase",
                    ),
                ),
            ],
            options={
                "db_table": "usecase_metadata",
                "ordering": ["metadata_item__label"],
                "abstract": False,
                "unique_together": {("usecase", "metadata_item")},
            },
        ),
    ]
