# Generated by Django 5.0.4 on 2024-05-30 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePreviewDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_all_entries', models.BooleanField(default=True)),
                ('start_entry', models.IntegerField(default=0)),
                ('end_entry', models.IntegerField(default=10)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='preview_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='preview_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.resourcepreviewdetails'),
        ),
    ]
