# Generated by Django 5.0.4 on 2025-04-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_datasetmetadata_created_datasetmetadata_modified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usecase",
            old_name="description",
            new_name="summary",
        ),
        migrations.AlterField(
            model_name="usecase",
            name="running_status",
            field=models.CharField(
                choices=[
                    ("INITIATED", "Initiated"),
                    ("ON_GOING", "On Going"),
                    ("COMPLETED", "Completed"),
                    ("ON_HOLD", "On Hold"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="INITIATED",
                max_length=50,
            ),
        ),
    ]
