# Generated by Django 5.0.4 on 2024-06-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_resourcepreviewdetails_resource_preview_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='title',
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(max_length=75, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
