# Generated by Django 5.0.4 on 2024-08-16 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_organization_title_organization_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceChartDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('chart_type', models.CharField(choices=[('BAR_VERTICAL', 'Bar Vertical'), ('BAR_HORIZONTAL', 'Bar Horizontal'), ('LINE', 'Line'), ('COLUMN', 'Column')], default='BAR_HORIZONTAL', max_length=50)),
                ('x_axis_label', models.CharField(max_length=50)),
                ('y_axis_label', models.CharField(max_length=50)),
                ('show_legend', models.BooleanField(default=False)),
                ('aggregate_type', models.CharField(choices=[('NONE', 'None'), ('SUM', 'Sum'), ('AVERAGE', 'Average'), ('COUNT', 'Count')], default='NONE', max_length=50)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.resource')),
                ('x_axis_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='x_column', to='api.resourceschema')),
                ('y_axis_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='y_column', to='api.resourceschema')),
            ],
        ),
    ]
