# Generated by Django 5.0.4 on 2025-04-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_rename_description_usecase_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="version",
            field=models.CharField(default="v1.0", max_length=50),
        ),
        migrations.CreateModel(
            name="ResourceVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.CharField(max_length=50)),
                ("commit_hash", models.CharField(max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("change_description", models.TextField(blank=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.resource",
                    ),
                ),
            ],
            options={
                "db_table": "resource_version",
                "unique_together": {("resource", "version_number")},
            },
        ),
    ]
