# Generated by Django 5.0.4 on 2024-08-16 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_resourcechartdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='x_axis_label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='y_axis_label',
            field=models.CharField(default='', max_length=50),
        ),
    ]
