# Generated by Django 5.0.4 on 2025-04-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0022_resource_version_resourceversion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usecase",
            name="summary",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
