# Generated by Django 5.0.4 on 2024-08-16 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_resourcechartdetails_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='x_axis_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='x_column', to='api.resourceschema'),
        ),
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='y_axis_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='y_column', to='api.resourceschema'),
        ),
    ]
