# Generated by Django 5.0.4 on 2025-04-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_alter_organization_organization_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="completed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usecase",
            name="started_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
