# Generated by Django 5.0.4 on 2024-09-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_resourcechartdetails_x_axis_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcechartdetails',
            name='region_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='api.resourceschema'),
        ),
        migrations.AddField(
            model_name='resourcechartdetails',
            name='value_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='value', to='api.resourceschema'),
        ),
        migrations.AlterField(
            model_name='resourcechartdetails',
            name='chart_type',
            field=models.CharField(choices=[('BAR_VERTICAL', 'Bar Vertical'), ('BAR_HORIZONTAL', 'Bar Horizontal'), ('LINE', 'Line'), ('ASSAM_DISTRICT', 'Assam District'), ('ASSAM_RC', 'Assam Rc')], default='BAR_HORIZONTAL', max_length=50),
        ),
    ]
