# Generated by Django 5.0.4 on 2024-10-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_resourcechartdetails_region_column_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
