# Generated by Django 5.0.4 on 2025-04-30 07:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_usecase_completed_on_usecase_started_on"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="contributors",
            field=models.ManyToManyField(
                blank=True,
                related_name="contributed_usecases",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
