# Generated by Django 5.0.4 on 2024-10-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_metadata_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='data_type',
            field=models.CharField(choices=[('STRING', 'String'), ('NUMBER', 'Number'), ('SELECT', 'Select'), ('MULTISELECT', 'Multiselect'), ('DATE', 'Date'), ('URL', 'Url')], max_length=50),
        ),
    ]
