# Generated by Django 5.0.4 on 2025-04-30 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_usecase_contributors"),
    ]

    operations = [
        migrations.CreateModel(
            name="UseCaseOrganizationRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[("SUPPORTER", "Supporter"), ("PARTNER", "Partner")],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.organization",
                    ),
                ),
                (
                    "usecase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.usecase"
                    ),
                ),
            ],
            options={
                "verbose_name": "UseCase Organization Relationship",
                "verbose_name_plural": "UseCase Organization Relationships",
                "db_table": "usecase_organization_relationship",
                "unique_together": {("usecase", "organization", "relationship_type")},
            },
        ),
        migrations.AddField(
            model_name="usecase",
            name="organizations",
            field=models.ManyToManyField(
                blank=True,
                related_name="related_usecases",
                through="api.UseCaseOrganizationRelationship",
                to="api.organization",
            ),
        ),
    ]
