# Generated by Django 5.0.4 on 2024-10-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_metadata_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='validator_options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='validator',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
