# Generated by Django 5.0.4 on 2025-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_dataset_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="github_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="linkedin_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="twitter_profile",
            field=models.URLField(blank=True, null=True),
        ),
    ]
