# Generated by Django 5.0.4 on 2025-05-21 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_organization_github_profile_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resourcechartdetails",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("BAR", "Bar"),
                    ("LINE", "Line"),
                    ("BAR_VERTICAL", "Bar Vertical"),
                    ("BAR_HORIZONTAL", "Bar Horizontal"),
                    ("GROUPED_BAR_VERTICAL", "Grouped Bar Vertical"),
                    ("GROUPED_BAR_HORIZONTAL", "Grouped Bar Horizontal"),
                    ("MULTILINE", "Multiline"),
                    ("ASSAM_DISTRICT", "Assam District"),
                    ("ASSAM_RC", "Assam Rc"),
                    ("TREEMAP", "Treemap"),
                ],
                default="BAR_HORIZONTAL",
                max_length=50,
            ),
        ),
    ]
