# Generated by Django 5.0.4 on 2025-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_usecase_user_alter_resourcechartdetails_chart_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcechartdetails",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="resourcechartimage",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                max_length=50,
            ),
        ),
    ]
