# Generated by Django 5.0.4 on 2025-05-27 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_resourcechartdetails_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.organization",
            ),
        ),
    ]
