# Generated by Django 5.0.4 on 2025-06-13 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_usecase_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="UseCaseDashboard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("link", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "usecase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to="api.usecase",
                    ),
                ),
            ],
            options={
                "db_table": "usecase_dashboard",
                "ordering": ["created"],
            },
        ),
    ]
