# Generated by Django 5.0.4 on 2025-06-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_usecasedashboard"),
    ]

    operations = [
        migrations.AddField(
            model_name="usecase",
            name="platform_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
