# Generated by Django 5.0.4 on 2025-12-24 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_sdg_dataset_geographies_usecase_geographies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("REGISTERED", "Registered"),
                    ("VALIDATING", "Validating"),
                    ("ACTIVE", "Active"),
                    ("AUDITING", "Auditing"),
                    ("APPROVED", "Approved"),
                    ("FLAGGED", "Flagged"),
                    ("DEPRECATED", "Deprecated"),
                ],
                default="REGISTERED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "version",
                    models.CharField(help_text="Version number (e.g., 1.0.0)", max_length=50),
                ),
                (
                    "version_notes",
                    models.TextField(blank=True, help_text="Changelog/notes for this version"),
                ),
                ("supports_streaming", models.BooleanField(default=False)),
                (
                    "max_tokens",
                    models.IntegerField(
                        blank=True, help_text="Maximum tokens supported", null=True
                    ),
                ),
                (
                    "supported_languages",
                    models.JSONField(default=list, help_text="List of supported language codes"),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        default=dict, help_text="Expected input format and parameters"
                    ),
                ),
                (
                    "output_schema",
                    models.JSONField(default=dict, help_text="Expected output format"),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict, help_text="Additional version-specific metadata"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("REGISTERED", "Registered"),
                            ("VALIDATING", "Validating"),
                            ("ACTIVE", "Active"),
                            ("AUDITING", "Auditing"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("DEPRECATED", "Deprecated"),
                        ],
                        default="REGISTERED",
                        max_length=20,
                    ),
                ),
                (
                    "is_latest",
                    models.BooleanField(
                        default=False, help_text="Whether this is the latest version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="api.aimodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Model Version",
                "verbose_name_plural": "AI Model Versions",
                "ordering": ["-created_at"],
                "unique_together": {("ai_model", "version")},
            },
        ),
        migrations.CreateModel(
            name="VersionProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("OPENAI", "Openai"),
                            ("LLAMA_OLLAMA", "Llama Ollama"),
                            ("LLAMA_TOGETHER", "Llama Together"),
                            ("LLAMA_REPLICATE", "Llama Replicate"),
                            ("LLAMA_CUSTOM", "Llama Custom"),
                            ("CUSTOM", "Custom"),
                            ("HUGGINGFACE", "Huggingface"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "provider_model_id",
                    models.CharField(
                        blank=True,
                        help_text="Provider's model identifier (e.g., gpt-4, claude-3-opus)",
                        max_length=255,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is the primary provider for the version",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hf_use_pipeline",
                    models.BooleanField(default=False, help_text="Use Pipeline inference API"),
                ),
                (
                    "hf_auth_token",
                    models.CharField(
                        blank=True,
                        help_text="Huggingface Auth Token for gated models",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "hf_model_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AutoModelForCausalLM", "Causal Language Modeling Head"),
                            (
                                "AutoModelForSeq2SeqLM",
                                "Sequence-To-Sequence Language Modeling Head",
                            ),
                            ("AutoModelForSequenceClassification", "Sequence Classification Head"),
                            ("AutoModelForNextSentencePrediction", "Next Sentence Prediction Head"),
                            ("AutoModelForMultipleChoice", "Multiple Choice Head"),
                            ("AutoModelForTokenClassification", "Token Classification Head"),
                            ("AutoModelForQuestionAnswering", "Question Answering Head"),
                            ("AutoModelForMaskedLM", "Masked Language Modeling Head"),
                        ],
                        help_text="Specify model head to use",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "hf_attn_implementation",
                    models.CharField(
                        blank=True,
                        default="flash_attention_2",
                        help_text="Attention Function",
                        max_length=255,
                    ),
                ),
                (
                    "framework",
                    models.CharField(
                        blank=True,
                        choices=[("pt", "PyTorch"), ("tf", "TensorFlow")],
                        help_text="Framework (PyTorch or TensorFlow)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "config",
                    models.JSONField(default=dict, help_text="Provider-specific configuration"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="providers",
                        to="api.aimodelversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Version Provider",
                "verbose_name_plural": "Version Providers",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
