# Generated by Django 5.0.4 on 2025-12-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_aimodel_status_aimodelversion_versionprovider"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelversion",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("DEVELOPMENT", "Development"),
                    ("TESTING", "Testing"),
                    ("BETA", "Beta Testing"),
                    ("STAGING", "Staging"),
                    ("PRODUCTION", "Production"),
                    ("DEPRECATED", "Deprecated"),
                    ("RETIRED", "Retired"),
                ],
                default="DEVELOPMENT",
                help_text="Current lifecycle stage of this version",
                max_length=20,
            ),
        ),
    ]
