# Generated by Django 5.0.4 on 2025-12-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_aimodelversion_lifecycle_stage"),
    ]

    operations = [
        migrations.AddField(
            model_name="versionprovider",
            name="api_auth_header_name",
            field=models.CharField(
                default="Authorization",
                help_text="Header name for authentication (e.g., Authorization, X-API-Key)",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_auth_type",
            field=models.CharField(
                choices=[
                    ("BEARER", "Bearer"),
                    ("API_KEY", "Api Key"),
                    ("BASIC", "Basic"),
                    ("OAUTH2", "Oauth2"),
                    ("CUSTOM", "Custom"),
                    ("NONE", "None"),
                ],
                default="BEARER",
                help_text="Authentication type for API calls",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_endpoint_url",
            field=models.URLField(
                blank=True,
                help_text="API endpoint URL (e.g., https://api.openai.com/v1/chat/completions)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_headers",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional headers to include in requests"
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_http_method",
            field=models.CharField(
                choices=[("GET", "Get"), ("POST", "Post"), ("PUT", "Put")],
                default="POST",
                help_text="HTTP method for API calls",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_key",
            field=models.CharField(
                blank=True,
                help_text="API key or token (encrypted at rest)",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_key_prefix",
            field=models.CharField(
                blank=True,
                default="Bearer",
                help_text="Prefix for API key (e.g., Bearer, Token)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_request_template",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Request body template with placeholders like {input}, {prompt}",
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_response_path",
            field=models.CharField(
                blank=True,
                help_text="JSON path to extract response (e.g., choices[0].message.content)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="api_timeout_seconds",
            field=models.IntegerField(default=60, help_text="Request timeout in seconds"),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="hf_device_map",
            field=models.CharField(
                blank=True,
                default="auto",
                help_text="Device map for model loading (auto, cpu, cuda)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="hf_torch_dtype",
            field=models.CharField(
                blank=True,
                default="auto",
                help_text="Torch dtype (auto, float16, float32, bfloat16)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="versionprovider",
            name="hf_trust_remote_code",
            field=models.BooleanField(
                default=True, help_text="Trust remote code when loading model"
            ),
        ),
        migrations.AlterField(
            model_name="versionprovider",
            name="config",
            field=models.JSONField(
                default=dict, help_text="Additional provider-specific configuration"
            ),
        ),
    ]
