# Generated by Django 5.0.4 on 2026-01-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_promptdataset_dataset_dataset_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promptdataset",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HEALTHCARE", "Healthcare"),
                    ("EDUCATION", "Education"),
                    ("LEGAL", "Legal"),
                    ("FINANCE", "Finance"),
                    ("AGRICULTURE", "Agriculture"),
                    ("ENVIRONMENT", "Environment"),
                    ("GOVERNMENT", "Government"),
                    ("TECHNOLOGY", "Technology"),
                    ("SCIENCE", "Science"),
                    ("SOCIAL_SERVICES", "Social Services"),
                    ("TRANSPORTATION", "Transportation"),
                    ("ENERGY", "Energy"),
                    ("GENERAL", "General"),
                    ("OTHER", "Other"),
                ],
                help_text="Domain or category (e.g., healthcare, education, legal)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="promptdataset",
            name="prompt_format",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INSTRUCTION", "Instruction"),
                    ("CHAT", "Chat"),
                    ("COMPLETION", "Completion"),
                    ("FEW_SHOT", "Few Shot"),
                    ("CHAIN_OF_THOUGHT", "Chain Of Thought"),
                    ("ZERO_SHOT", "Zero Shot"),
                    ("OTHER", "Other"),
                ],
                help_text="Format of prompts (e.g., instruction, chat, completion)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="promptdataset",
            name="target_model_types",
            field=models.JSONField(
                blank=True,
                help_text="List of AI model types these prompts are designed for (e.g., ['GPT', 'LLAMA'])",
                null=True,
            ),
        ),
    ]
