# Generated by Django 5.0.4 on 2026-01-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_alter_promptdataset_domain_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PromptResource",
            fields=[
                (
                    "resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="prompt_details",
                        serialize=False,
                        to="api.resource",
                    ),
                ),
                (
                    "prompt_format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("INSTRUCTION", "Instruction"),
                            ("CHAT", "Chat"),
                            ("COMPLETION", "Completion"),
                            ("FEW_SHOT", "Few Shot"),
                            ("CHAIN_OF_THOUGHT", "Chain Of Thought"),
                            ("ZERO_SHOT", "Zero Shot"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Format of prompts in this file (e.g., instruction, chat, completion)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "has_system_prompt",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the prompts in this file include system-level instructions",
                    ),
                ),
                (
                    "has_example_responses",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the prompts in this file include example/expected responses",
                    ),
                ),
                (
                    "avg_prompt_length",
                    models.IntegerField(
                        blank=True,
                        help_text="Average character length of prompts in this file",
                        null=True,
                    ),
                ),
                (
                    "prompt_count",
                    models.IntegerField(
                        blank=True, help_text="Total number of prompts in this file", null=True
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Prompt Resource",
                "verbose_name_plural": "Prompt Resources",
                "db_table": "prompt_resource",
            },
        ),
        migrations.RemoveField(
            model_name="promptdataset",
            name="avg_prompt_length",
        ),
        migrations.RemoveField(
            model_name="promptdataset",
            name="has_example_responses",
        ),
        migrations.RemoveField(
            model_name="promptdataset",
            name="has_system_prompt",
        ),
        migrations.RemoveField(
            model_name="promptdataset",
            name="prompt_count",
        ),
        migrations.RemoveField(
            model_name="promptdataset",
            name="prompt_format",
        ),
        migrations.RemoveField(
            model_name="promptdataset",
            name="use_case",
        ),
    ]
