# Generated by Django 5.0.4 on 2026-01-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0042_promptresource_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promptdataset",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("RESEARCH", "Research"),
                    ("EDUCATION", "Education"),
                    ("EVALUATION", "Evaluation"),
                    ("OTHER", "Other"),
                ],
                help_text="Purpose of the prompt dataset",
                max_length=200,
                null=True,
            ),
        ),
    ]
