# Generated by Django 5.0.4 on 2026-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_promptdataset_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aimodel",
            name="input_schema",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Expected input format and parameters",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional metadata (training data info, limitations, etc.)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="output_schema",
            field=models.JSONField(
                blank=True, default=dict, help_text="Expected output format", null=True
            ),
        ),
        migrations.AlterField(
            model_name="aimodel",
            name="supported_languages",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of supported language codes (e.g., ['en', 'es', 'fr'])",
                null=True,
            ),
        ),
    ]
