# Generated by Django 5.0.4 on 2026-02-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_aimodel_input_schema_alter_aimodel_metadata_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodel",
            name="domain",
            field=models.CharField(
                blank=True,
                choices=[
                    ("HEALTHCARE", "Healthcare"),
                    ("EDUCATION", "Education"),
                    ("LEGAL", "Legal"),
                    ("FINANCE", "Finance"),
                    ("AGRICULTURE", "Agriculture"),
                    ("ENVIRONMENT", "Environment"),
                    ("GOVERNMENT", "Government"),
                    ("TECHNOLOGY", "Technology"),
                    ("SCIENCE", "Science"),
                    ("SOCIAL_SERVICES", "Social Services"),
                    ("TRANSPORTATION", "Transportation"),
                    ("ENERGY", "Energy"),
                    ("GENERAL", "General"),
                    ("OTHER", "Other"),
                ],
                help_text="Domain or category (e.g., healthcare, education, legal)",
                max_length=200,
                null=True,
            ),
        ),
    ]
