# Generated by Django 5.0.4 on 2026-04-30 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_aimodel_domain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collaborative",
            name="slug",
            field=models.SlugField(
                blank=True,
                max_length=75,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Slug must be lowercase and contain only alphanumeric characters and hyphens.",
                        regex="^[a-z0-9]+(?:-[a-z0-9]+)*$",
                    )
                ],
            ),
        ),
    ]
