# Generated by Django 5.0.4 on 2026-08-26 08:13

import api.utils.file_paths
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_collaborative_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=75, unique=True)),
                ("description", models.CharField(blank=True, max_length=1000, null=True)),
                ("slug", models.SlugField(max_length=75, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Resource Type",
                "verbose_name_plural": "Resource Types",
                "db_table": "resource_type",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300)),
                ("description", models.TextField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("authors", models.JSONField(blank=True, default=list)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "license",
                    models.CharField(
                        choices=[
                            ("GOVERNMENT_OPEN_DATA_LICENSE", "Government Open Data License"),
                            ("CC_BY_4_0_ATTRIBUTION", "Cc By 4 0 Attribution"),
                            (
                                "CC_BY_SA_4_0_ATTRIBUTION_SHARE_ALIKE",
                                "Cc By Sa 4 0 Attribution Share Alike",
                            ),
                            (
                                "OPEN_DATA_COMMONS_BY_ATTRIBUTION",
                                "Open Data Commons By Attribution",
                            ),
                            ("OPEN_DATABASE_LICENSE", "Open Database License"),
                        ],
                        default="CC_BY_4_0_ATTRIBUTION",
                        max_length=50,
                    ),
                ),
                ("external_source_link", models.URLField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                        default="DRAFT",
                        max_length=50,
                    ),
                ),
                ("download_count", models.IntegerField(default=0)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "geographies",
                    models.ManyToManyField(
                        blank=True, related_name="publications", to="api.geography"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="api.organization",
                    ),
                ),
                (
                    "sectors",
                    models.ManyToManyField(
                        blank=True, related_name="publications", to="api.sector"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="api.resourcetype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Publication",
                "verbose_name_plural": "Publications",
                "db_table": "publication",
                "ordering": ["-modified"],
            },
        ),
        migrations.AddField(
            model_name="collaborative",
            name="publications",
            field=models.ManyToManyField(blank=True, to="api.publication"),
        ),
        migrations.AddField(
            model_name="usecase",
            name="publications",
            field=models.ManyToManyField(blank=True, to="api.publication"),
        ),
        migrations.CreateModel(
            name="PublicationBlock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "block_type",
                    models.CharField(
                        choices=[("FILE", "File"), ("YOUTUBE", "Youtube")], max_length=20
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=api.utils.file_paths._publication_block_directory_path,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=300)),
                ("file_format", models.CharField(blank=True, max_length=50)),
                ("file_size", models.BigIntegerField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("youtube_video_id", models.CharField(blank=True, max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="api.publication",
                    ),
                ),
            ],
            options={
                "db_table": "publication_block",
                "ordering": ["position"],
                "indexes": [
                    models.Index(
                        fields=["publication", "position"], name="publication_publica_bbb551_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="publicationblock",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("block_type", "FILE"),
                        ("youtube_url__isnull", True),
                        models.Q(("file", ""), _negated=True),
                    ),
                    models.Q(
                        ("block_type", "YOUTUBE"), ("file", ""), ("youtube_url__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="publicationblock_file_xor_youtube",
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["organization", "-modified"], name="publication_organiz_c16e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["user", "-modified"], name="publication_user_id_02e48d_idx"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["status"], name="publication_status_2449b8_idx"),
        ),
    ]
