# Generated by Django 5.0.4 on 2026-09-30 08:07

import api.utils.file_paths
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_resourcetype_publication_collaborative_publications_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalContributor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        max_length=300,
                        null=True,
                        upload_to=api.utils.file_paths._external_contributor_directory_path,
                    ),
                ),
                ("organization", models.CharField(blank=True, max_length=255, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "external_contributor",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="publication",
            name="contributors",
            field=models.ManyToManyField(
                blank=True, related_name="contributed_publications", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddConstraint(
            model_name="externalcontributor",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="unique_external_contributor_email_lower",
            ),
        ),
        migrations.AddField(
            model_name="collaborative",
            name="external_contributors",
            field=models.ManyToManyField(
                blank=True, related_name="collaboratives", to="api.externalcontributor"
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="external_contributors",
            field=models.ManyToManyField(
                blank=True, related_name="publications", to="api.externalcontributor"
            ),
        ),
        migrations.AddField(
            model_name="usecase",
            name="external_contributors",
            field=models.ManyToManyField(
                blank=True, related_name="usecases", to="api.externalcontributor"
            ),
        ),
    ]
