# Generated by Django 5.0.4 on 2026-09-23 20:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_resourcetype_publication_collaborative_publications_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DatasetSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("KAGGLE", "Kaggle"),
                            ("HUGGINGFACE", "Huggingface"),
                            ("GITHUB", "Github"),
                        ],
                        max_length=50,
                    ),
                ),
                ("source_identifier", models.CharField(max_length=300)),
                ("source_url", models.URLField(max_length=500)),
                ("source_homepage", models.URLField(blank=True, max_length=500)),
                ("revision", models.CharField(blank=True, max_length=64)),
                ("source_author", models.CharField(blank=True, max_length=300)),
                ("source_license", models.CharField(blank=True, max_length=300)),
                ("source_readme", models.TextField(blank=True)),
                ("citation", models.TextField(blank=True)),
                ("languages", models.JSONField(blank=True, default=list)),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_last_updated", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source",
                        to="api.dataset",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="imported_dataset_sources",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "dataset_source",
                "indexes": [
                    models.Index(
                        fields=["platform", "source_identifier"],
                        name="dataset_sou_platfor_38ca23_idx",
                    )
                ],
            },
        ),
    ]
