# Generated by Django 5.0.4 on 2026-10-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_externalcontributor_publication_contributors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collaborative",
            name="organization",
        ),
        migrations.AddField(
            model_name="collaborative",
            name="designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
