# Generated by Django 5.0.4 on 2026-10-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_remove_organization_add_designation"),
    ]

    operations = [
        migrations.AddField(
            model_name="externalcontributor",
            name="designation",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="externalcontributor",
            name="has_approved",
            field=models.BooleanField(default=False),
        ),
    ]
