# Generated by Django 5.0.4 on 2026-10-01 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_add_has_approved_designation_external_contributor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="externalcontributor",
            name="organization",
        ),
    ]
