# Generated by Django 5.0.4 on 2026-10-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_publicationblock_title_description"),
        ("api", "0051_remove_organization_from_external_contributor"),
    ]

    operations = []
