# Generated by Django 5.0.4 on 2026-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_seed_resource_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='summary',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
