# Generated by Django 5.0.4 on 2026-10-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_usecase_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborative',
            name='summary',
            field=models.TextField(blank=True, max_length=200000, null=True),
        ),
    ]
