# Generated by Django 5.0.4 on 2026-10-05 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_platform_import"),
        ("api", "0052_merge_20261001_1137"),
    ]

    operations = []
