blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/CivicDataLab/DataSpaceBackend/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: mailto:tech@civicdatalab.in
    about: Please report security vulnerabilities via email
