# Generated by Django 5.0.4 on 2025-04-28 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="ds_user",
        ),
    ]
