# Generated by Django 5.0.4 on 2025-05-09 14:11

import api.utils.file_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="twitter_profile",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.utils.file_paths._user_profile_image_directory_path,
            ),
        ),
    ]
