# Generated by Django 5.0.4 on 2025-05-27 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0003_user_github_profile_user_linkedin_profile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_tracking_enabled", models.BooleanField(default=False)),
                ("consent_given_at", models.DateTimeField(blank=True, null=True)),
                ("consent_updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consent_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("consent_user_agent", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Consent",
                "verbose_name_plural": "User Consents",
                "db_table": "user_consent",
            },
        ),
    ]
